name: influxdb3
services:
  influxdb3-core:
    container_name: influxdb3-core
    build:
      context: .
      dockerfile: influx.Dockerfile
    ports:
      - 8181:8181
    volumes:
      - ./data:/home/influxdb3/.influxdb

  python-backend:
    container_name: influxdb3-python-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - influxdb3-core
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - INFLUX_HOST=http://influxdb3-core:8181
      - INFLUX_DATABASE=demo
